### ISSUE TITLE
LipshitzVAEs with convolutional architeture

### ISSUE THREAD

**Issue by amruz** [FabianBarrett/Lipschitz_VAEs#1]
Hi, I was just trying to run the same code with convolutional based architecture and it seems like the training time is really expensive. Have you ever tried using convolutional architecture? I guess the orthonormalization after each layer is the bottleneck here. Any pointers here? Thanks in advance!

**Comment by FabianBarrett** [comment]
Hi @amruz — thanks for your interest in our work. Yes, training is expensive. I don't have specific pointers other than to note we found considerable speedups running things on GPU (as opposed to CPU).

**Comment by amruz** [comment]
Thank you for the quick reply! Do you have a rough estimate of the time taken for 1 epoch in your case?

**Comment by FabianBarrett** [comment]
My co-author ran our experiments on GPU, so I'm not sure about time estimates for 1 epoch in that case. On CPU,
* for MNIST,
* for a simple feed-forward network with three layers and hidden dimension ~500,
* during the fine-tuning stage of training (with a large number of Bjorck Orthonormalization iterations),

1 epoch took would take up to an hour.

I should stress that the code for which this runtime estimate applies was not very optimized, so I'm sure some gains could be made.

**Comment by amruz** [comment]
Thanks!
